### ISSUE TITLE
Debugger do not work properly

### ISSUE THREAD

**Issue by kiela** [johnbintz/guard-rails#14]
As in topic, debugger do not work properly with guard, it means it stops for a short while and then render rest of website, so you can not type anything in debugger.

Some info:
- Test app can be found here: https://github.com/kiela/guard-rails-myapp
- Logs from setup app can be found here: https://github.com/kiela/guard-rails-myapp/blob/master/install.log

Used:
- rvm 1.6.10
- ruby 1.9.2-p180 
- rails 3.2.1

**Comment by johnbintz** [comment]
That's not something I'll be able to easily fix. Guard::Rails forks a new Rails process, which becomes non-interactive. All Guard::Rails does is manage the Rails process itself, it has no knowledge of the app. If you want to use debugger, you'll probably have to run the app the old-fashioned way.

**Comment by ches** [comment]
Hmm, the `debugger` option for the guard and its entry in the README are misleading, then. :wink:

**Comment by johnbintz** [comment]
Might want to talk to @joelmoss who added that and must have gotten it working somehow.

**Comment by ches** [comment]
I suppose it might work for a remote debugger... it does work and Joel can show how on the wiki that'd be awesome :smile:
