### ISSUE TITLE
How would one use bundle exec?

### ISSUE THREAD

**Issue by arronmabrey** [johnbintz/guard-rails#15]
How would one use bundle exec before the server command?

**Comment by johnbintz** [comment]
Under normal use, you'd run Guard using `bundle exec` and that would bring in your app's Bundled environment. Then running `rails` uses the version of Rails specified in your Gemfile.

**Comment by arronmabrey** [comment]
Of course what was I thinking ;-)

On Sat, Mar 10, 2012 at 11:02 AM, John Bintz <
reply@reply.github.com
