### ISSUE TITLE
Ensure Guard returns a boolean status

### ISSUE THREAD

**Issue by johnbintz** [johnbintz/guard-rails#3]
For now, have it always return `true`.

**Comment by netzpirat** [comment]
John, since version 0.8.0 this is obsolete. The return value is only passed to a defined Guard hook, but it isn't evaluated in Guard itself. When something wrong and you want to stop the other Guards within the same group, you have to throw a symbol:

```
throw :task_has_failed
```

Thanks for the great Guard.

**Comment by johnbintz** [comment]
Yup, I'll nuke this ticket and get the other guards updated. Thanks!
