### ISSUE TITLE
add other server option

### ISSUE THREAD

**Issue by artemk** [johnbintz/guard-rails#4]
https://github.com/tehpeh/guard-rails/commit/372e2cd24a292997669741b877763df11071743f

**Comment by johnbintz** [comment]
Can you put this into a pull request? I'll merge it in once you do.

**Comment by dbgrandi** [comment]
+1 to this.

**Comment by artemk** [comment]
I have asked "tehpeh" to do that. But if he won't do it till Thursday, i will fork from his fork and make a pull request.

**Comment by johnbintz** [comment]
This got merged in a while ago, so closing.
