### ISSUE TITLE
Rails server should be (re)started on reload?

### ISSUE THREAD

**Issue by tehpeh** [johnbintz/guard-rails#6]
Hi John,

Just thinking that the rails server should be started and restarted on guard's reload command rather than run_all?

This would mean when you reload guard with r+enter it will restart the server, but just hitting enter will not do anything. 

What do you think?

For me that makes sense if I also run rspec and cucumber in my guardfile, so enter runs all the tests, and r+enter reloads the server and spork.

**Comment by johnbintz** [comment]
For me, having Rails restart on `run_all` means that I can change some file that Rails doesn't autoload, like something in `lib` or `config`, and Rails restarts without me needing to do a thing. Reloading the Guardfile is another place that a Rails reload may make sense, too, especially now that I'm playing with different servers for Rails development. For my normal workflow, though, `run_all` makes more sense than `reload`.

Whoever gets to adding that to guard-rails first wins. :)
