### ISSUE TITLE
Do not restart Rails when changing config/locales

### ISSUE THREAD

**Issue by karlfreeman** [johnbintz/guard-rails#7]
Just a thought while I was editing some small locale changes that reloading the whole of rails might be overkill for lazy loadable locale changes.

**Comment by johnbintz** [comment]
Try blocking it in your Guardfile (untested):

``` ruby
watch(%r{^(config|lib)/.*\.([^.]+)$}) { |m| m[0] if m[2] != 'yml' && !m[0]['locales'] }
```

**Comment by karlfreeman** [comment]
Worked right off the bat, Nice one. Whats even nicer is the LiveReload kicking in too. Perhaps this would be good 'Tip' for the bottom of the readme?

**Comment by johnbintz** [comment]
I'll think about actually making it the default. When I initially wrote this, I wasn't doing a lot with locales in the projects I was working on, but it's a good idea. The only thing it won't catch right now is if a locale file is added, which Rails doesn't seem to pick up while running. I'll ponder a bit.
