### ISSUE TITLE
it doesn't support rails 2.*

### ISSUE THREAD

**Issue by tian-im** [johnbintz/guard-rails#9]
will this be possible?

**Comment by johnbintz** [comment]
Sure it's possible, but I probably won't be able to get to it myself for a few weeks, as jasmine-headless-webkit is taking up all my OSS time at the moment. If you want to try adding it yourself, start by looking here:

https://github.com/johnbintz/guard-rails/blob/master/lib/guard/rails/runner.rb#L43

You'd either need to have a :rails2 option, or find some way to autodetect what version of Rails the current project is using.

**Comment by tian-im** [comment]
yep, sure, will do
